spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456aA@
    url: jdbc:mysql://localhost:3306/demo
  jpa:
    database: mysql
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/change-log-root.xml
