spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456aA@
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/change-log-root.xml
