version: '3.8'
services:
  postgres-demo:
    image: postgres:latest
    # volumes:
    #   - ~/volumes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456aA@
    ports:
      - "5432:5432"
